"""Data structures for the Project Memory / Codebase Cognition layer.
We keep them lightweight – only the fields needed for hierarchical IDs, source location, and minimal metadata.
"""

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import List, Optional, Dict

class SymbolType(Enum):
    MODULE = auto()
    CLASS = auto()
    FUNCTION = auto()
    METHOD = auto()

    def __str__(self) -> str:
        return self.name.lower()

@dataclass
class CodeSymbol:
    """A single code entity extracted from the AST.

    Attributes
    ----------
    symbol_id: str
        Stable hierarchical identifier, e.g. ``auth.jwt.generate_token``.
    symbol_type: SymbolType
        MODULE / CLASS / FUNCTION / METHOD.
    file_path: str
        Absolute path to the source file.
    name: str
        Simple name of the symbol (module name, class name, function name).
    start_line: int
        First line of the definition in the source file.
    end_line: int
        Last line of the definition.
    parent_id: Optional[str]
        Symbol ID of the container (module for classes, class for methods, etc.).
    docstring: Optional[str]
        Extracted docstring, if any.
    signature: Optional[str]
        Raw source line that defines the symbol (e.g. ``def foo(a, b)``).
    content_hash: str
        SHA‑256 hash of the full source snippet – used for change detection.
    dependencies: List[str] = field(default_factory=list)
        List of symbol IDs that this symbol imports or calls.
    summary: Optional[str] = None
        Human‑readable short description generated by the summarizer.
    """

    symbol_id: str
    symbol_type: SymbolType
    file_path: str
    name: str
    start_line: int
    end_line: int
    parent_id: Optional[str] = None
    docstring: Optional[str] = None
    signature: Optional[str] = None
    content_hash: str = ""
    dependencies: List[str] = field(default_factory=list)
    summary: Optional[str] = None

    def to_metadata(self) -> Dict:
        """Return a dict suitable for OMem ``metadata`` field.
        Includes all structural information needed for graph queries.
        """
        return {
            "symbol_id": self.symbol_id,
            "symbol_type": str(self.symbol_type),
            "file_path": self.file_path,
            "name": self.name,
            "start_line": self.start_line,
            "end_line": self.end_line,
            "parent_id": self.parent_id,
            "docstring": self.docstring,
            "signature": self.signature,
            "content_hash": self.content_hash,
            "dependencies": self.dependencies,
            "summary": self.summary,
            "is_code_symbol": True,
        }

    def to_memory_content(self) -> str:
        """Compact string representation stored as the memory ``content``.
        We keep it short – only the signature and docstring (if any).
        """
        parts = []
        if self.signature:
            parts.append(self.signature)
        if self.docstring:
            parts.append(self.docstring.strip())
        return "\n".join(parts) if parts else self.name
